### ISSUE TITLE
FYI: npm publish errors

### ISSUE THREAD

**Issue by rarkins** [semantic-release/npm#112]
This somewhat of an FYI regarding an npm bug that impacts semantic-release.

## Current behavior

An `npm` bug (it seems) is causing partial semantic release publishes

## Expected behavior

I'm not sure whether it's appropriate for `semantic-release` to implement a workaround for this, but ideally it would continue with the release somehow.

## Environment

Using latest `semantic-release` on TravisCI, and I'm seeing this same problem: https://github.com/npm/npm/issues/20787

The result is:

1. The release notes are not published to GitHub when it first fails
2. The next runs attempts to publish "over the top" and gets rejected for duplicate version

**Comment by pvdlg** [comment]
Closing as it's an issue in npm and there is nothing we can do.
If we were to do something it would be to implement a mechanism to recover from a partial release. See https://github.com/semantic-release/semantic-release/issues/896
