### ISSUE TITLE
`npm version` hook support: preversion, version, postversion

### ISSUE THREAD

**Issue by dwieeb** [semantic-release/npm#114]
This package uses a custom function to set the `package.json` version:

https://github.com/semantic-release/npm/blob/5951b30f1f47d3c3570fbf5feb7808518b9a3bbd/lib/prepare.js#L8

It does this instead of using `npm version`, likely because `npm version` does many undesirable things, but it seems our npm scripts are not being run. Our use case is we need to modify another file with the chosen version. Our scripts look like this:

```
  "scripts": {
    "sync-version": "sync-version package.json other-file",
    "version": "npm run sync-version && git add other-file",
```

Before, the `version` script would run during `npm version`, [as documented](https://docs.npmjs.com/cli/version).

With `semantic-release`, we're unsure how to do this. Right now, we are using [`@semantic-release/exec`](https://github.com/semantic-release/exec), but it would be nice to know which npm scripts are executed in which stages and which are not.

**Comment by travi** [comment]
i typically use `prepack` to do tasks like building a bundle  before publishing. i've also successfully used `prepublishOnly`, but prefer `prepack` because it runs when packing locally too. would those scripts accomplish what you're looking for?

**Comment by pvdlg** [comment]
What @travi described is the recommended approach.

For info, that's also mentioned in our FAQ: https://github.com/semantic-release/semantic-release/blob/caribou/docs/support/FAQ.md#how-can-i-use-a-npm-build-script-that-requires-the-packagejsons-version-

Please let us know if that answer your question, and close the issue if it does.

**Comment by dwieeb** [comment]
Thanks for your quick replies!

The root confusion to me is that some npm scripts during the release process appear to run, and some don't, which seems inconsistent.

- [ ] `preversion`/`version`/`postversion` would happen in the `prepare` step, if it was supported.
- [x] `prepublishOnly`/`prepack` happen in the `publish` step.

---

As far as I can tell, [since `@semantic-release/git` makes a release commit during the `prepare` step](https://github.com/semantic-release/git#semantic-releasegit), there isn't an easy way of including file changes from the versioning step of the release process in the release commit.

**Comment by dwieeb** [comment]
> I can't remember why we made the choice of using custom code there.

I'm guessing `npm version` isn't used because it does too much: it also makes a git tag and a commit, but I believe it can be disabled via `npm --no-git-tag-version <version>`.
