### ISSUE TITLE
*d.ts files are not published

### ISSUE THREAD

**Issue by developer239** [semantic-release/npm#132]
**package.json**

```
"main": "./lib/index.js",
"module": "./lib/index.es.js",
"types": "lib/index.d.ts",
```

**.releaserc**

```
{
  "plugins": [
    ["@semantic-release/commit-analyzer", {
      "preset": "angular",
      "releaseRules": [
        { "type": "docs", "release": "patch" },
        { "type": "refactor", "release": "patch" },
        { "type": "style", "release": "patch" },
        { "type": "chore", "release": "patch" },
        { "type": "build", "release": "patch" },
        { "type": "ci", "release": "patch" }
      ]
    }],
    "@semantic-release/release-notes-generator",
    "@semantic-release/changelog",
    "@semantic-release/npm",
    ["@semantic-release/git", {
      "assets": ["lib/**/*.{js,ts,css}", "CHANGELOG.md", "package.json"]
    }]
  ]
}
```
**ui-library [local]**

![image](https://user-images.githubusercontent.com/14946081/50540961-27ad8e00-0b9c-11e9-9131-ca9317b72a0e.png)

**ui-library [node_modules]**
![image](https://user-images.githubusercontent.com/14946081/50540958-106ea080-0b9c-11e9-826e-192aedc2d90b.png)

How do I include `ts` files in my npm build? I thought that `"assets": ["lib/**/*.{js,ts,css}", "CHANGELOG.md", "package.json"]` will do the trick.

**Comment by pvdlg** [comment]
The `assets` option is used to includes files in the GitHub release with the [`@semantic-release/github`](https://github.com/semantic-release/github) plugin or to commit those file to your repo with the [`@semantic-release/git`](https://github.com/semantic-release/git) plugin.

What's included in the npm package is not related to **semantic-release**, it's configured via npm. See https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package.

You also need to make sure your compiled are generated before running `semantic-release`.
