### ISSUE TITLE
Which version of `semantic-release` to update `package.json`?

### ISSUE THREAD

**Issue by rodoabad** [semantic-release/npm#143]
Does this require Git version 2.x? I'm trying to test this on an older version of Git pre 2.x and the only version of `semantic-release` working is `15.1.0`. While it is able to publish to NPM, it isn't updating the version on `package.json`.

**Comment by travi** [comment]
these might be helpful for what youre looking for. regardless, git v2.0.0 was released on May 28, 2014 and some pretty major security issues have been fixed since then. your time would probably be better invested in upgrading to a supported version of git

* https://semantic-release.gitbook.io/semantic-release/support/faq#why-is-the-package-jsons-version-not-updated-in-my-repository
* https://github.com/semantic-release/semantic-release/issues/856

**Comment by rodoabad** [comment]
Matttttttt! I'll probably update this CI instance. On other instances where we're using the latest version of Git we don't have this issue.

**Comment by pvdlg** [comment]
semantic-release require git 2.0.0 at minimum. We started to enforce that in some 15.x version.
Before that, semantic-release with Git v1.x.x was working "sometimes". So we decided to enforce it.

**Comment by patrickleet** [comment]
I have git 2.2.1 and I'm seeing this issue - is this a bug?

![image](https://user-images.githubusercontent.com/474827/55518252-562a8180-5641-11e9-96b4-f9d21b38a75b.png)

**Comment by rodoabad** [comment]
@patrickleet that's on the same node and workspace?

**Comment by patrickleet** [comment]
@rodoabad it is

**Comment by patrickleet** [comment]
this worked a couple weeks ago also

**Comment by patrickleet** [comment]
https://github.com/sindresorhus/execa/issues/196

perhaps this is related?

I added some logs to see what was going on more:

```

+ DEBUG='semantic-release*'

+ semantic-release --debug

[11:15:02 PM] [semantic-release] › ℹ  Running temp-semantic-release-debug version 15.13.4

{ stdout: 'git version 1.8.3.1' }

{ versions: [ '1.8.3' ] }

{ gitVersion: '1.8.3' }

[semantic-release]: Git version 2.0.0 is required. Found 1.8.3.

script returned exit code 1
```

The related issue describes execa modifying paths and causing the wrong version to be used.

**Comment by patrickleet** [comment]
That was it!

```
+ DEBUG='semantic-release*'

+ semantic-release --debug

[11:35:22 PM] [semantic-release] › ℹ  Running temp-semantic-release-debug version 15.13.5

{ stdout: 'git version 2.21.0' }

{ versions: [ '2.21.0' ] }

{ gitVersion: '2.21.0' }

2019-04-04T23:35:22.411Z semantic-release:config load config from: undefined

2019-04-04T23:35:22.414Z semantic-release:config options values: { branch: 'master',

```

Will make a PR
