### ISSUE TITLE
Private registry as an environment variable or plugin config

### ISSUE THREAD

**Issue by charliebravodev** [semantic-release/npm#147]
Hello,

The native NPM api uses the `.npmrc` file or `publishConfig` object from the `package.json` to set publishing configuration (registry, authentication...). I somehow disagree with this setup as I believe deployment configuration shouldn't be embedded in project files, but set at runtime in the CI environment.

You have done a great job at respecting NPM's API. I was wondering if it would be possible to be able to set the NPM `registry` directly in the plugin configuration or via an environment variable and use it in the `--registry` option of most NPM commands. 

What is your take on this ? Would you consider it as an additional feature ?

All the best and thanks for the great plugin !

**Comment by gr2m** [comment]
I’d like to be able to configure the registry for a different reason: I want to be able to publish the same package to both the npm registry as well as GitHub’s npm registry. 

I’ve tried to use the `NPM_CONFIG_REGISTRY` environment variable but it isn’t used by this plugin.

Adding a configuration option would be the cleanest option I think. I’ll get a pull request going for further discussion

**Comment by pvdlg** [comment]
See conversation from #161

The registry can be set in an `.npmrc` file that can live in the home directory of the CI user. This way the registry config is associated with your environment rather than with the project.
