### ISSUE TITLE
version or tag

### ISSUE THREAD

**Issue by naerion89** [semantic-release/npm#162]
Hi,

i use semantic-release to generate release candidate (RC) and release.
When i release (RC or not), i want to update version in package.json.

Problem : I make a release candidate, i specify a tagFormat v{version}-RC but package.json is updated with version (no version-RC).

Is-it a bug or the appropriate behavior ?

Regards,

**Comment by pvdlg** [comment]
prerelease (with a -something suffix) will be supported in v16. It's currently available on the `@beta` dist-tag.
