### ISSUE TITLE
Can this be fixed somehow, It will save some "git revert" efforts.

### ISSUE THREAD

**Issue by nozelrosario** [semantic-release/npm#165]
This just bit me:

> I just had a case where a user mistakenly didn't have public rights to the npm package (after changing tokens and using a different user for the token a couple weeks ago).
> 
> However, the `verifyConditions` didn't catch this. It was only caught when the npm publish step failed with a 403 error message stating the user doesn't have publish rights.
> 
> That meant the the git tag was still pushed to the repo, leaving the tag out of sync. Retrying the build would then not publish, because the tag was already pushed.
>

_Originally posted by @felixfbecker in https://github.com/semantic-release/npm/issues/4#issuecomment-407507829_

**Comment by travi** [comment]
ive run into similar situations for unrelated reasons. outside of a change to semantic-release, i've found it simple enough to simply delete the git tag after resolving the npm issues and just re-running the build

**Comment by nozelrosario** [comment]
Yes, deleting the tag + reverting the version increment commit + re-run the release build command works, but i just need to save that extra effort.

**Comment by travi** [comment]
> reverting the version increment commit

it wasn't clear from your post above what revert effort you were running into. by default, semantic-release only adds the tag. without extra commits being added to the repository, i havent had a need to do any reverting beyond the tag removal. since youve configured the version bump additionally, my suggestion doesnt fit your case quite as well

**Comment by gr2m** [comment]
I don’t understand why you open another issue if #4 is still open. Feel free to investigate how to resolve the problem, I think Pierre made some suggestions. Pull requests welcome :)
