### ISSUE TITLE
Security vulverabilities from "tar" and "fstream"

### ISSUE THREAD

**Issue by archemiro** [semantic-release/npm#167]
I am using semantic-release `^15.13.16` as a devDependency, when run `npm audit` I get:

> found 12 high severity vulnerabilities

All from semantic-release/npm, from "tar" and "fstream" packages.

In my `package-lock.json` I have: 

`
...
"@semantic-release/npm": {
  "version": "5.1.10",
  ...
`

**Comment by gr2m** [comment]
neither `tar` nor `fstream` are direct dependencies of semantic-release, there is nothing we can do. You have to delete your lock file and your node_modules folder then install from scratch. It might fix the audit problems. If not, find out with `npm ls tar` and `npm ls fstream` what is preventing the dependencies to be updated or a previous version to be pinned

**Comment by ZebraFlesh** [comment]
I dug into this and found the following:
```
npm ls tar
nope@4.8.2 C:\Users\nope\git\nope
+-- @semantic-release/npm@5.1.10
| `-- npm@6.9.0
|   +-- node-gyp@3.8.0
|   | `-- tar@2.2.1
|   +-- pacote@9.5.0
|   | `-- tar@4.4.8  deduped
|   `-- tar@4.4.8
+-- babel-jest@24.8.0
| `-- @jest/transform@24.8.0
|   `-- jest-haste-map@24.8.0
|     `-- UNMET OPTIONAL DEPENDENCY fsevents@1.2.8
|       `-- UNMET OPTIONAL DEPENDENCY node-pre-gyp@0.12.0
|         `-- UNMET OPTIONAL DEPENDENCY tar@4.4.8
`-- node-sass@4.12.0
  `-- node-gyp@3.8.0
    `-- tar@2.2.2
```

Doing an `npm uninstall @semantic-release/npm semantic-release node-sass` fixes the vulnerabilities. As soon as I `npm install --save-dev @semantic-release/npm semantic-release`, they come back. The issue seems to stem from the latest version of npm depending on an old version of node-gyp. :(
