### ISSUE TITLE
new dependency to execa@2 breaks backward compatibility!

### ISSUE THREAD

**Issue by guardine** [semantic-release/npm#172]
the new dependency to execa@2 in 15.1.12 implies a new node version restriction to node 8.
the backward compatibility to version 5.1.11 is broken.

**Comment by gr2m** [comment]
semantic-release requires Node 8 LTS. We have defined 8.3 as the minimal version as it was the LTS version at this time, it is 8.16 at this point. Unless there is a reason that you cannot bump your Node 8 version in your CI I do not agree that this update warrants a breaking change.

I have edited your comment as it was unnecessary aggressive. Please remain kind and on subject, this is a volunteer-run project, remember that you are not entitled to anyones attention.
