### ISSUE TITLE
Are public organizations supported?

### ISSUE THREAD

**Issue by manast** [semantic-release/npm#178]
I am getting a payment required error while trying to publish to a public organisation:
```
    'npm ERR! 402 Payment Required - PUT https://registry.npmjs.org/@taskforcesh%2fqueue-commands - You must sign up for private packages\n' +
```
according to npm documentation it should be possible to publish using:
```
npm publish --access public
```
is this supported?

**Comment by travi** [comment]
simply [define `publishConfig`](https://semantic-release.gitbook.io/semantic-release/support/faq#how-can-i-set-the-access-level-of-the-published-npm-package) in your `package.json`

**Comment by manast** [comment]
ok, I see it is a duplicate of this one: https://github.com/semantic-release/npm/issues/33
thanks.
