### ISSUE TITLE
Publish using existing credentials?

### ISSUE THREAD

**Issue by bpholt** [semantic-release/npm#193]
Is it possible to publish npm artifacts using existing credentials in place? We have an existing build set up to use `npm publish` with an encrypted `.npmrc` file containing the necessary credentials, decrypted by the build agent into `.npmrc`. This is working well, but as far as we can tell so far, it doesn't map well into setting the environment variable this plugin looks for.

We're thinking about using `semantic-release/git` to do the commits and push tags to our internal git servers, and then use `semantic-release/exec` to call out to `npm publish` (using `npmPublish` set to false). But this seems to overlap with @pvdlg's advice in https://github.com/semantic-release/npm/issues/191#issuecomment-533280008, so I wanted to make sure there wasn't a better  way.

**Comment by pvdlg** [comment]
This is not possible currently. We always expect to have `NPM_TOKEN` set and we always add the credentials to `.npmrc` based on that.

What's the reason to favor an encrypted `.npmrc` over and `NPM_TOKEN` environment variable?

**Comment by bpholt** [comment]
Our build system currently has no way of injecting environment variables in a secure way, so we'd have to write some script to do the same decryption and then safely set the environment in a way that doesn't show up in the build logs. 

More than anything, though, is inertia… this is working, and the developers involved don't have access to the credentials to easily switch it to something else.

**Comment by pvdlg** [comment]
What is your build system?
You currently use an encrypted `.npmrc`, how do you decrypt it without using environment variables? What solution do you to pass a value (the decryption key) to the environment in a way that doesn't show up in the build logs?

**Comment by pvdlg** [comment]
Actually what I said before is incorrect. If the credential are already set up in `.npmrc` we do not make any modification. We look for the `.npmrc` set up via `NPM_CONFIG_USERCONFIG` or the one at the root of your project.

See https://github.com/semantic-release/npm/blob/01267047b3e8e9287c0b56722fbe63d946acd76d/lib/set-npmrc-auth.js#L15

So what you are asking already works.

I'm going to close issue but feel free to comment further if you need help to figure out why something is not working in your case.
