### ISSUE TITLE
How is the current version determined?

### ISSUE THREAD

**Issue by jedmao** [semantic-release/npm#195]
I'm having issues publishing my first `@semantic-release/npm` triggered publish, because it's running `npm version 1.0.0 --no-git-tag-version` when the `v1.0.0` tag already exists in [my repo, `@jedmao/location`](https://github.com/jedmao/location). As such, I'm getting the following error:

```
npm ERR! Version not changed, might want --allow-same-version
```

Of course, I don't want to use `--alow-same-version`, because, as stated before, tag `v1.0.0` already exists and my `package.json` file already says `"version": "1.0.0"`.

How do I introduce `@semantic-release/npm` to an existing project with an already-published version? I'm triggering this all with `npx semantic-release` in the [GitHub CI environment](https://github.com/jedmao/location/runs/234891901).

**Comment by gr2m** [comment]
Hi Jed,

I'd do the following:

1. run `npx semantic-release-cli setup`. Among other things, it will replace the current value in "version" with "0.0.0-semantically-released", as the version is dynamically determined and not checked in to git by default
2. Make sure your last git tag & npm version are in sync.
3. Push new commits which have one of the conventions that trigger a new version such as `fix: do the right thing`

That should be it.

**Comment by jedmao** [comment]
Thanks @gr2m. It actually changed my `package.json` version to `0.0.0-development`, but `npx semantic-release` still tried to publish `v1.0.0`, which already exists. How do I convince semantic-release that `v2.0.0` is the version I want published, as that is the next breaking version?

**Comment by gr2m** [comment]
Can you share the full log output of `npx semantic-release --debug`?

**Comment by jedmao** [comment]
I think it would be better to just link to it?

https://github.com/jedmao/location/runs/235134229#step:5:1

**Comment by jedmao** [comment]
I'll do you one better. Here's [a link to the GitHub CI log](https://github.com/jedmao/location/runs/235140021#step:5:115).

**Comment by jedmao** [comment]
Notice how the `release-notes-generator` knows that my current version is `v1.0.0` [here](https://github.com/jedmao/location/runs/235140021#step:5:104).

**Comment by gr2m** [comment]
Curious why it gets the authentication error but still continues:
https://github.com/jedmao/location/runs/235140021#step:5:54

Then it says it found the v1.0.0 release tag, but below it says "No git tag version found" 0_o
https://github.com/jedmao/location/runs/235140021#step:5:74

That's why it tries to release a v1.0.0, it does not recognize the current tag as a release, I don't understand why, I must be missing something

**Comment by gr2m** [comment]
I would recommend to add semantic-release to your devDependencies though, there will be breaking changes in future and if you run `npx semantic-release` without having a version defined in your package.json, things might start breaking randomly. 

Just for debugging, could you maybe remove the shared config setting?

https://github.com/jedmao/location/blob/e18f3e9cce002af20433b1ce20b80adc329305f0/package.json#L47-L50

**Comment by jedmao** [comment]
I can't say for sure which of [these changes](https://github.com/jedmao/location/commit/56bd1693927fb75dcab3c9dcf8899a69218dd562) fixed the issue, but I think it must be the newly-created `GH_TOKEN` instead of the limited `GITHUB_TOKEN`. Are we still waiting on [this guy](https://github.com/semantic-release/semantic-release/issues/974#issuecomment-525362404)?

**Comment by jedmao** [comment]
The authentication error never got fixed, but I'm not sure it matters. It still published.

**Comment by gr2m** [comment]
> Are we still waiting on [this guy](https://github.com/semantic-release/semantic-release/issues/974#issuecomment-525362404)?

v15.13.24 should work with the `GITHUB_TOKEN` provided in actions, I use that myself in several of my repositories
