### ISSUE TITLE
Version 15.13.27 depends (indirectly) on a package that has high vulnerability issues (https-proxy-agent) 

### ISSUE THREAD

**Issue by hernanif1** [semantic-release/npm#206]
Reopened from https://github.com/semantic-release/semantic-release/issues/1327

Hi,
I have semantic-release installed in version 15.13.27. This module depends on @semantic-release/npm, which, somewhere along the dependency tree, depends on https-proxy-agent in version 2.x.

NPM reports (with npm audit) that https-proxy-agent has a High vulnerability has stated here (https://nodesecurity.io/advisories/1184). This vulnerability is fixed in version >=3.0.0

Is it possible to incorporate this fix in semantic-release? I'm not sure of the implications because 3.0.0 is a major version and probably has breaking changes.

Thank you!

**Comment by pvdlg** [comment]
Why reopening semantic-release/semantic-release#1327 while it has been answered and closed? That just cost time and create frustration...

Reopening the same issue won't change the fact that the problematic dependency is defined in npm and this project, as it's not the npm project, can't update the dependencies defined in the npm project.

**Comment by hernanif1** [comment]
Hi @pvdlg,
My intention with this issue was to follow npm dependency and update it here when it become available.
If this is update here it's not necessary please just inform that it will be automaticly updated.
There is no necessity to be rude.

**Comment by protoEvangelion** [comment]
@pvdlg how will people track this issue if you closed this and https://github.com/semantic-release/semantic-release/issues/1327

**Comment by pvdlg** [comment]
By opening an issue with npm as I suggested and by tracking it.

You won't be able to track anything in a semantic-release issue as the problem is not in semantic-release and a fix in npm will not update the semantic-release issue.

**Comment by hernanif1** [comment]
**Suggestion of workaround:**
In my CI/CD I'm using the command `npm audit --production`
In this way all **dev-dependencies** are ignored (if it makes sense for you)
