### ISSUE TITLE
Machine-In-The-Middle on @semantic-release/npm dependency

### ISSUE THREAD

**Issue by nbalduzzi** [semantic-release/npm#212]
Hi, im having a security issue in the dependency. Also have the same issue on other @semantic-release dependencies.

This is the report that i have.

High **Machine-In-The-Middle**
**Package** https-proxy-agent
**Patched in** >=2.2.3
**Dependency of** @semantic-release/npm [dev]
**Path:** @semantic-release/npm > npm > libnpmteam >  npm-registry-fetch > make-fetch-happen > https-proxy-agent
**More info:** https://npmjs.com/advisories/1184

**Note:** Im using node v10.16.0 version.

**Comment by pvdlg** [comment]
The dependency is a sub-dependency of `npm` on which this plugin depends.
There is nothing we can do here other than not depending on `npm`  which is impossible for obvious reasons.

The issue is that `npm`  itself use outdated dependencies. Please open an issue in the npm repo.
