### ISSUE TITLE
NPM automation token

### ISSUE THREAD

**Issue by radum** [semantic-release/npm#277]
NPM introduced automation tokens https://github.blog/changelog/2020-10-02-npm-automation-tokens/

This means we can keep our 2FA for login and publish and use automation tokens to bypass 2FA for publishing.

I did that on a test project and `semantic-release/npm` fails at the verify auth step for npm.

I was wondering it this is miss configuration on my part if there is work that needs to be done to support the new tokens.

The setup is simple, I am using 2FA for both publish and login on NPM

![image](https://user-images.githubusercontent.com/46779/95470074-426b8400-0978-11eb-89b3-09cd058acd95.png)

and my test repo has enabled the automation token option from settings.

![image](https://user-images.githubusercontent.com/46779/95469963-1f40d480-0978-11eb-9076-4f43172c6cf5.png)

As for my semantic-release config

```
{
	"branches": ["+([0-9])?(.{+([0-9]),x}).x", "main", "next", "next-major", { "name": "beta", "prerelease": true }, { "name": "alpha", "prerelease": true }],
	"plugins": [
		"@semantic-release/commit-analyzer",
		"@semantic-release/release-notes-generator",
		[
			"@semantic-release/changelog",
			{
				"changelogTitle": "# Changelog\n\nAll notable changes to this project will be documented in this file. See\n[Conventional Commits](https://conventionalcommits.org) for commit guidelines."
			}
		],
		[
			"@semantic-release/npm",
			{
				"tarballDir": "pack"
			}
		],
		[
			"@semantic-release/github",
			{
				"assets": "pack/*.tgz"
			}
		],
		[
			"@semantic-release/git",
			{
				"message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
			}
		]
	]
}
```

**Comment by radum** [comment]
So it looks like if I use `npm whoami` (and I am successfully logged in via npm login) it works ok.

If I use the generated whoami from the lib:

```
npm whoami --userconfig /private/var/folders/jj/temppathhere/.npmrc --registry https://registry.npmjs.org
npm ERR! code E403
npm ERR! 403 403 Forbidden - GET https://registry.npmjs.org/-/whoami
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/radu.micu/.npm/_logs/2020-10-08T15_43_06_087Z-debug.log
```

I get the err above.

I double checked the above mentioned npmrc file and it has this content:

```
@radum:registry=https://registry.npmjs.org/
package-lock=false

//registry.npmjs.org/:_authToken = ${NPM_TOKEN}
```

Evaluating the `${NPM_TOKEN}` env var give me the correct automation token I have generated. I double checked this.

Even if I paste the token manually in that temp file I get the same err.

I think this is because npm whoami doesn't support automation tokens to be used. But the publish command will be ok with it.

Is my thinking correct here?

**Comment by gr2m** [comment]
It sounds like it, most likely the verify step of the `@semantic-release/npm` step is failing. I think we use the `whoami` endpoint for that. Could you check if we can change the implementation to make it work with the new tokens?

**Comment by radum** [comment]
@gr2m So it looks like an automation token can only download packages and publish new ones so there is no way we can validate them. If they don't work the publish will fail and that is it.

I guess the only way we could fix this, is to add a new option flag and say skip the token validation as I am using an automation one. And if the publish fails because I have submitted the wrong one fail as it normally does.

I can't think of a why that could be used to achieve this. Even if you dry-un publish or pack commands they will not fail I think if you don't have an valid token (the dry run I mean).

**Comment by gr2m** [comment]
Thanks for investigating, I’ll reach out to the npm folks

**Comment by gr2m** [comment]
I've contact the npm folks about the problem of verification, I'd prefer to await their response. They just shipped npm7 so they had other priorities, but I hope they get back to me soon now. If they enable a way to verify a token, adding this feature will become obsolete, so I'd prefer not to add it in the first place if we can help it

**Comment by Markus-Ende** [comment]
Thanks for clarifying this! I was wondering why my initial CI setup fails until I found this issue. Maybe you could add a disclaimer for that, in the meantime?

**Comment by gr2m** [comment]
I think someone said the `/whoami` endpoint was enabled meanwhile. Does the problem still occur for you?

**Comment by Markus-Ende** [comment]
> I think someone said the `/whoami` endpoint was enabled meanwhile. Does the problem still occur for you?

yes, I just checked, and still get the `403 Forbidden - GET https://registry.npmjs.org/-/whoami`

**Comment by Nargonath** [comment]
FWIW here is a travis pipeline failing for whoami when using the automation token: https://travis-ci.org/github/Nargonath/cra-build-watch/jobs/740138487.

**Comment by Nargonath** [comment]
Good news, thanks @gr2m.

**Comment by jkroepke** [comment]
Unless its resolved, how to disable the validation inside semantic-release?

**Comment by radum** [comment]
You can't @jkroepke we are hoping this will be sorted out soon.

**Comment by Nargonath** [comment]
You'd need to lower your 2FA settings in order to publish again and also generate another token with the proper auth permissions.

**Comment by hamzahamidi** [comment]
Just curious. Why do we need the whoami to publish?

**Comment by travi** [comment]
> Why do we need the whoami to publish?

this check enables verifying that a valid token is available before starting the release process. without this pre-check, part of the release process is already complete before the publish would fail due to lack of permissions.

**Comment by jkroepke** [comment]
I did not tried yet.

For unknown reasons, `registry.npmjs.org` additionally listen on port 8443.

Until https://github.com/npm/feedback/discussions/44 is resolved it's possible to set `NPM_CONFIG_REGISTRY=https://registry.npmjs.org:8443/` which skip the verification step and enables the usable of npm automation tokens.

Before using this workaround, read the posts above.

**Comment by hamzahamidi** [comment]
> > Why do we need the whoami to publish?
> 
> this check enables verifying that a valid token is available before starting the release process. without this pre-check, part of the release process is already complete before the publish would fail due to lack of permissions.

It would be great if we have a npm endpoint just for checking the validity of the token and get the rules associated with.

**Comment by grantila** [comment]
> Yes, we'll open up whoami for automation tokens. I don't have an ETA quite yet, but it shouldn't be too long.

It's been weeks now and no progress. Is there any workaround, can we e.g. disable the verification somehow?

**Comment by gr2m** [comment]
@grantila the workaround is not to use the npm automation token for semantic-release yet

**Comment by hamzahamidi** [comment]
In the mean time you can generate tokens for Publish only. 

**NB: Two Factor Authentication needs to be disabled for it to work with CI**

**Comment by travi** [comment]
i haven't confirmed, but it looks like this should be unblocked

> As part of a set of changes, we have deployed support for the /whoami endpoint for Automation Tokens. Please let me know if you're still having trouble.

https://github.com/npm/feedback/discussions/44#discussioncomment-136539

**Comment by gr2m** [comment]
If someone could confirm, that'd be ace ☝🏼

**Comment by bniedermeyer** [comment]
Looks like it is now working on releases verifying against `registry.npmjs.org`.

**Comment by grantila** [comment]
Yes, it works like a charm now

**Comment by hamzahamidi** [comment]
Tested with publish token, It works. It still needs to be tested with Two Factor Authentication enabled.

**Comment by bniedermeyer** [comment]
The project I tested with has 2FA enabled.

**Comment by Nargonath** [comment]
That's great news! Thanks for the change. 🎉

**Comment by austince** [comment]
@cecilemuller - did the workaround added in https://github.com/wildpeaks/package-frozen/commit/37c3fbf2acb7fb5b6b8f70203b878f2e38966008 work for you? Is the https://github.com/semantic-release/npm/issues/277#issuecomment-723431906 workaround still necessary? I'm seeing errors trying to release [chai-http](https://github.com/chaijs/chai-http/runs/1995002882) with an automation token and am wondering if it's something in our setup that's wrong or if there are still intricacies here.

**Comment by cecilemuller** [comment]
@austince Oh wow, January feels so long ago that I don't even recall that commit 😄 

The good news is [I use this](https://github.com/wildpeaks/package-frozen/blob/master/.github/workflows/publish.yml#L87) now:
````yml
- name: Publish
  run: |
    echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
    npm publish --tag ${{ steps.deployment.outputs.tag }}
  env:
    NPM_TOKEN: ${{ secrets.NPM_DEPLOY_KEY }}
````

I also use this code in [this repo](https://github.com/wildpeaks/package-tsconfig/blob/main/.github/workflows/publish.yml#L82) and was able to publish 4 days ago, so I'm sure this should be working.

**Comment by austince** [comment]
> @austince Oh wow, January feels so long ago that I don't even recall that commit 😄

😅 indeed it was. Thanks for the quick reply and pointers! I think I misunderstood though -- I thought you were also using semantic-release.

**Comment by cecilemuller** [comment]
> I think I misunderstood though -- I thought you were also using semantic-release.

Not at the moment (even though I switched to semantic commit messages because I used to want to), in the end I prefer passing the version number to the Publish action using a `workflow_dispatch` input (I'm so glad Github added it a few months ago) and it deduces whether it's a stable or preview release from it, this way I don't have the version number anywhere in the source code given it felt redundant with Github Releases which already contains the version number of the latest release.

But I might add it one day, the automated changelog would come in handy.
