### ISSUE TITLE
npm automation tokens cannot create dist-tags

### ISSUE THREAD

**Issue by lapa182** [semantic-release/npm#298]
Hello, after we updated the latest semantic-release version when we merge from development to master, we are not being able to distribute from development to latest. It's a private package, current using automation token (2FA). It publishes normally to development.

Current versions installed:

"@semantic-release/commit-analyzer": "^8.0.1"
"@semantic-release/npm": "^7.0.8"
"@semantic-release/release-notes-generator": "^9.0.1"
"semantic-release": "^17.3.0"

Configuration in the package.json:

```
"release": {
    "branches": [
      "master",
      "development"
    ]
  },
  "publishConfig": {
    "registry": "https://registry.npmjs.org/"
  },
```

**Logs**

```[8:28:39 AM] [semantic-release] [@semantic-release/npm] › ℹ  Adding version 0.5.3 to npm registry on dist-tag latest
npm ERR! code E403
npm ERR! 403 403 Forbidden - GET https://registry.npmjs.org/-/package/@harveynichols%2fweb-ui-library/dist-tags
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-11-27T08_28_39_961Z-debug.log
[8:28:39 AM] [semantic-release] › ✖  Failed step "addChannel" of plugin "@semantic-release/npm"
[8:28:39 AM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 1: npm dist-tag add @harveynichols/web-ui-library@0.5.3 latest --userconfig /tmp/31cf1458465efa93278297bc89edb6b6/.npmrc --registry https://registry.npmjs.org/
npm ERR! code E403
npm ERR! 403 403 Forbidden - GET https://registry.npmjs.org/-/package/@harveynichols%2fweb-ui-library/dist-tags
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy.```

**Comment by gr2m** [comment]
My guess is that semantic-release tried to create a "development" dist-channel on your package, and the new automation token does not permit that. Could that be possible? If that's the case, I can check in with the npm team, they recently made a change to permit the `GET /user` endpoint with the automation token, I think it would be within the scope to permit creating dist-tags, too.

It would be easy enough to check if creating a dist-tag with an automation token is possible. If anyone could test that out I'd appreciate it

**Comment by lapa182** [comment]
> My guess is that semantic-release tried to create a "development" dist-channel on your package, and the new automation token does not permit that. Could that be possible? If that's the case, I can check in with the npm team, they recently made a change to permit the `GET /user` endpoint with the automation token, I think it would be within the scope to permit creating dist-tags, too.
> 
> It would be easy enough to check if creating a dist-tag with an automation token is possible. If anyone could test that out I'd appreciate it

let me do that for you, wasn't able to test today but will test tomorrow and add the feedback here on the issue!

**Comment by lapa182** [comment]
@gr2m I just made some round of tests:

with automation token: it returns 403 every single time in all `npm dist-tags` commands.
with publish token (because I have 2FA enable): was requiring OTP, so it's was working as expected.

**Comment by gr2m** [comment]
Thank you for confirming. I'll check in with npm team

**Comment by gr2m** [comment]
I created a feedback discussion here that you can follow: https://github.com/npm/feedback/discussions/108. I'll elevate if the team doesn't get back to it within a week. Thanks again Igo!

**Comment by MylesBorins** [comment]
This should be fixed now!

**Comment by gr2m** [comment]
confirmed, thank you!
