### ISSUE TITLE
Broken sentence in error message

### ISSUE THREAD

**Issue by domoritz** [semantic-release/npm#322]
https://github.com/semantic-release/npm/blob/493fbad4e2bff62603854a49c670bc70ec895fb7/lib/definitions/errors.js#L39

**Comment by gr2m** [comment]
Thank you! Could you send a pull request to fix the message?

**Comment by domoritz** [comment]
I couldn't yesterday since I was still struggling to make sense of what I am supposed to do. I reworded the message so it would have helped me. Please take a look https://github.com/semantic-release/npm/pull/323.
