### ISSUE TITLE
how to publish @org scoped public packages

### ISSUE THREAD

**Issue by arlac77** [semantic-release/npm#33]
I am unable to publish a org scored package
```txt
@kronos-integration/test-step
```

```txt
402\nnpm ERR! code E402\nnpm ERR! You must sign up for private packages : @kronos-integration/test-step\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /home/travis/.npm/_logs/2018-01-05T21_04_12_179Z-debug.log\n',
  failed: true,
```

is there a way to configure the equivalent of:

```sh
npm publish --access public
```

**Comment by pvdlg** [comment]
Yes, see our freshly release documentation including that question in the FAQ: https://semantic-release.gitbooks.io/semantic-release/content/docs/support/FAQ.html#how-can-i-set-the-access-level-of-the-published-npm-package

**Comment by jloewe** [comment]
**The original link is dead.** Use this link instead: https://semantic-release.gitbook.io/semantic-release/support/faq#how-can-i-set-the-access-level-of-the-published-npm-package
