### ISSUE TITLE
Publishing private NPM packages are not working 

### ISSUE THREAD

**Issue by GBeushausen** [semantic-release/npm#339]
Hi,

im trying to publish private NPM packages from Bitbucket Pipelines. However i receive some errors that "root" cannot be published:

`    'npm ERR! code E403\n' +
    'npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/root - You do not have permission to publish "root". Are you logged in as the correct user?\n' +
    'npm ERR! 403 In most cases, you or one of your dependencies are requesting\n' +
    'npm ERR! 403 a package version that is forbidden by your security policy.\n' +`

This is my config:

`                      - npm config set -g "//registry.npmjs.org/:_authToken" '${NPM_TOKEN}'
                      - npm install
                      - npx lerna bootstrap
                      - npm run test
                      - npx semantic-release --debug
`
Of course the token is set correct, the steps above all work. What can i do to make it work?

**Comment by travi** [comment]
> You do not have permission to publish "root". Are you logged in as the correct user?

do you have the `name` property defined correctly in your `package.json`? according to the error, you are attempting to publish https://www.npmjs.com/package/root, which i assume you are not the owner of. Are you maybe missing your scope in the name?

**Comment by GBeushausen** [comment]
Thanks, the name of my main package.json file is indeed "root". But i'm using a Monorepo. I don't want to get the main package.json published, i want to get my packages published. Do i have to setup semantic release in each package.json of the corresponding packages?

**Comment by travi** [comment]
semantic-release has no official support for monorepos. there are some tools that have built some level of support on top of the official core, but we currently provide no official recommendation or support for those addons.

**Comment by GBeushausen** [comment]
OK, thanks for your help :-)
