### ISSUE TITLE
Publish to private repo

### ISSUE THREAD

**Issue by roigreenberg** [semantic-release/npm#347]
Hi.

I need to publish my package to a private repo, without configuring NPM_CONFIG_REGISTRY that will affect the rest of the operations.

Is there a way to change the configuration for that part only?

**Comment by dceballos24** [comment]
Hey there, this one is needed.

**Comment by roigreenberg** [comment]
It's been a year since I asked it :)
I no longer work at the same place, and I actually not sure what we did eventually, but I think we did manage to do what we wanted.
Thanks!
