### ISSUE TITLE
get-registry.js doesn't take into account NPM_CONFIG_USERCONFIG

### ISSUE THREAD

**Issue by jameshartig** [semantic-release/npm#349]
When `get-registry.js` looks for the registry it just looks at `./.npmrc` instead of taking into account `NPM_CONFIG_USERCONFIG`. This ends up requiring that you specify `NPM_CONFIG_REGISTRY` when you shouldn't have to because it's already in the alternative rc file specified by `NPM_CONFIG_USERCONFIG`.

**Comment by rodoabad** [comment]
@jameshartig are you able to put this in a sandbox repo so it can be easily reproduced?

**Comment by jameshartig** [comment]
@rodoabad it was actually easier to just fix it. I opened a PR.
