### ISSUE TITLE
publish references /tmp location for .npmrc

### ISSUE THREAD

**Issue by scottnath** [semantic-release/npm#368]
Hi,

When I get to the publish step, I am getting an error: `npm ERR! need auth You need to authorize this machine using npm adduser`

When I look at the output, I see this line:

`Failed step "publish" of plugin "@semantic-release/npm"
[5:04:45 PM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 1: npm publish /home/travis/build/ORG/REPO --userconfig /tmp/6eadfab29eecfc5883274e046652cb1c/.npmrc --tag prerelease --registry https://...registry`

I have tried many combinations and locations for `NPM_CONFIG_USERCONFIG` and tried using `NPM_TOKEN` but I keep getting the `adduser` error and I am unable to publish. I know that my .npmrc file works because I am able to log in to my registry, but it looks like when it goes to publish it's referencing the `/tmp/.../.npmrc` file every time, even if I use  `NPM_CONFIG_USERCONFIG` to tell the system to use a different config file.

Am I missing a setting or config somewhere that tells semantic-release/npm to use my file instead of the `tmp` one? Looking at [index.js](https://github.com/semantic-release/npm/blob/master/index.js) I can't see where that original `npmrc` variable is created, but I don't see how it is overwritten by my npmrc contents or file.

thank you!

**Comment by jamespantalones** [comment]
@scottnath i'm seeing same behavior... how did you solve?
