### ISSUE TITLE
ES Module

### ISSUE THREAD

**Issue by travi** [semantic-release/npm#436]
Part of our efforts to migrate `semantic-release` to native ES Modules: https://github.com/semantic-release/semantic-release/issues/2133

**Comment by hongaar** [comment]
Leaving a note here in case it is useful, I've just finished converting the `@semantic-release/npm` plugin to TypeScript + ESM (all tests are passing) here: https://github.com/hongaar/semantic-release-yarn/commit/ba1cc454f3f62e68e590daa26942beb8faedd529

Let me know if I can help with https://github.com/semantic-release/npm/pull/437

**Comment by gr2m** [comment]
Thanks! We don't want TypeScript but using your PR for reference will helpful nonetheless. We are working on the `semantic-release` package right now, but once that's done the npm core plugin will be one of the next

**Comment by hongaar** [comment]
I linked to the wrong commit above, the PR is here with all steps in separate commits: https://github.com/hongaar/semantic-release-yarn/pull/7

Some lessons learned when I hit an obstacle with `clear-module` (which only works in for `require`):

- in `test/integration.test.js` I used a cache buster instead:
  ```js
  t.context.m = await import(
    `../dist/index.js?update=${new Date()}-${new Date().getMilliseconds()}`
  );
  ```
- in `test/set-npmrc-auth.test.js` I set the tmp directories in a `before` hook for all tests and clean up test files in the `beforeEach` hook instead to resolve an issue with global state in the `rc` dep (which would cache the process.env.HOME directory and didn't pick up changes made in each subsequent test. `clear-module` recursively cleared all `require`d modules, I don't think a cache buster would work here)

**Comment by travi** [comment]
thanks again for this suggestion, @hongaar! i referenced it in [`63b4d54` (#437)](https://github.com/semantic-release/npm/pull/437/commits/63b4d5444bb4f812009e8a01c111411857501baf) now that i'm taking a look at the esm conversion of this plugin again
