### ISSUE TITLE
error @npmcli/arborist@4.1.1: The engine "node" is incompatible with this module

### ISSUE THREAD

**Issue by kunalnagar** [semantic-release/npm#446]
`@semantic-release/npm` version `7.1.3`

Hi folks,

I have a [PR opened by Renovate](https://github.com/kunalnagarco/healthie/pull/36) that refreshes the lockfile every month or so and with the recent update, the `yarn install --frozen-lockfile` command seems to be failing on node 15.x. As you can see, the error is:

```
$ yarn install --frozen-lockfile
yarn install v1.22.17
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error @npmcli/arborist@4.1.1: The engine "node" is incompatible with this module. Expected version "^12.13.0 || ^14.15.0 || >=16". Got "15.14.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

To understand where this error is originating from, I ran `yarn why @npmcli/arborist` and realized that it's used in this package, which is why I've created this issue to get more info:

```
$ yarn why @npmcli/arborist
yarn why v1.22.17
[1/4] 🤔  Why do we have the module "@npmcli/arborist"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@npmcli/arborist@4.1.1"
info Reasons this module exists
   - "@semantic-release#npm#npm" depends on it
   - Hoisted from "@semantic-release#npm#npm#@npmcli#arborist"
   - Hoisted from "@semantic-release#npm#npm#libnpmexec#@npmcli#arborist"
   - Hoisted from "@semantic-release#npm#npm#libnpmfund#@npmcli#arborist"
✨  Done in 0.67s.
```

Would any of y'all be able to provide more input on what might be happening here? Thanks!

**Comment by travi** [comment]
> Would any of y'all be able to provide more input on what might be happening here?

the error messages seem to explain most of the details i would try to cover. is there a specific detail that you are looking for more information about? considering that node v15 [is now EOL](https://nodejs.org/en/about/releases/) it seems like the best resolution for you would be to migrate to a supported node version.

**Comment by kunalnagar** [comment]
> considering that node v15 is now EOL

@travi - thanks for the response 🙂  it does make sense to remove node 15 from the matrix checks for the package now that it's EOL. From the error messages, it does seem that `arborist` itself has stopped supporting node 15 because of EOL. 

Closing this.
