### ISSUE TITLE
no-workspaces-update option

### ISSUE THREAD

**Issue by johngeorgewright** [semantic-release/npm#495]
A recent change to npm v8 runs an update, to any project that includes a `"workspaces"` property, when using the `npm version` command inside one of the configured "workspaces". I'm using `@semantic-release/npm` in a monorepo using the Yarn3 and this is now failing as my packages are linked together with a protocol that is not supported by NPM (and even if it were, I'd rather run this update with `yarn` and not `npm`).

It looks like this feature can be [turned off with a flag](https://docs.npmjs.com/cli/v8/commands/npm-version#workspaces-update) `--no-workspaces-update` when running `npm version`. Could this perhaps be an option for @semantic-release/npm?

**Comment by janpe** [comment]
We're having this same issue as well. @johngeorgewright did you manage to find a workaround for the time being?

**Comment by johngeorgewright** [comment]
@janpe, I ended up using a slightly more custom approach, with [@semantic-release/exec](https://github.com/semantic-release/exec). You can see [my config file here](https://github.com/johngeorgewright/runtyping/blob/master/release.config.js).

**Comment by travi** [comment]
please also refer to [this conversation](https://github.com/semantic-release/npm/pull/482#issuecomment-1158706304) about setting this option in the `.npmrc` file for the project. 

keep in mind that semantic-release does not officially support use in the context of a monorepo at this point, so we are also avoiding adding complexity to the project for needs that are specific to monorepos. we do want to avoid details that block semantic-release from being enhanced by community addons for use in such contexts, but the use of an `.npmrc` file to set this option should be enough to avoid a semantic-release specific option for this.
