### ISSUE TITLE
Lifetime scripts do not seem to execute

### ISSUE THREAD

**Issue by MichaelBrunn3r** [semantic-release/npm#507]
I have a little hacky setup because I use pnpm and other stuff, so I will try to explain my problem as best as I can.

1. I use typescript, so I transpile my code in the `prepack` lifecycle script
2. My package root is my ./dist directory containing the transpiled javascript. It does not contain e.g. package.json, so I also use `prepack` to copy all relevant files into the ./dist directory
3. semantic-release/npm first checks if a package.json exists in ./dist. Of course it doesn't because `prepack` didn't run yet, so instead run it manually as a step in my github action. Now semantic-release/npm doesn't complain anymore. Anoying but easy to fix
4. semantic-release/npm runs the `npm version` command on my ./dist/package.json. Cool, but it doesn't run the `postversion` script like the documentation said it would. So now my ./dist/package.json is not copied to ./package.json. I know that because semantic-release/git does not commit it but the release file *.tgz contains the correct updated package.json. 

So what I expected was:
- `npm version`
- `postversion` is automatically executed
- `npm pack`
- `prepack` is automatically executed beforehand

What I observed:
- `npm version`
- `npm pack`

```json
"release": {
		"branches": [
			"main"
		],
		"plugins": [
			"@semantic-release/commit-analyzer",
			"@semantic-release/release-notes-generator",
			"@semantic-release/changelog",
			[
				"@semantic-release/npm",
				{
					"pkgRoot": "./dist",
					"tarballDir": "."
				}
			],
			[
				"@semantic-release/github",
				{
					"assets": "*.tgz"
				}
			],
			[
				"@semantic-release/git",
				{
					"assets": [
						"package.json",
						"CHANGELOG.md"
					]
				}
			]
		]
	}
````

**Comment by travi** [comment]
> 2\. My package root is my ./dist directory containing the transpiled javascript. It does not contain e.g. package.json

why do you want to copy your `package.json` to the `dist/` folder? it is common to have built files in a `dist/` or similar folder, but that alone doesnt mean that you need to publish from that folder. as long as you define `main` or `exports` and ensure that the files referenced there are included in the package (like by including `dist/` in the `files` list in the `package.json`), you should be all set.

if you configure these details, you should be able to avoid most of the remaining complexity that you describe

**Comment by MichaelBrunn3r** [comment]
> why do you want to copy your package.json to the dist/ folder?

Because otherwise semantic-release/npm complains that no package.json exists. The package.json is in the root folder, but semantic-release/npm seems to search for it in the package root, so in ./dist.

> it is common to have built files in a dist/ or similar folder, but that alone doesnt mean that you need to publish from that folder

Yes, thats true, but my package has multiple entries. Not just one index.js, but multiple in different subfolders. having all these subfolders in ./dist/<subfolder>/index.js did not work for me. So I looked at other packages, like svelte. They publish straight from the ./dist folder. This fixed my problems with multiple roots.

**Comment by MichaelBrunn3r** [comment]
I wrote this at night after trying to get this to work for some time. A good night sleep helped me find the obvious problem.
