### ISSUE TITLE
a `Cannot read properties of null (reading 'matches'` error when using multi-semantic-release

### ISSUE THREAD

**Issue by arvinxx** [semantic-release/npm#540]
an error show when using multi-semantic-release

```
[multi-semantic-release]: Error: Command failed with exit code 1: npm version 2.2.7-beta.1 --userconfig /private/var/folders/3z/f7x4sr8n0qvfxw9jndvd6dj00000gn/T/30e5af0cadafdf31cb2c56c141c6a958/.npmrc --no-git-tag-version --allow-same-version
npm ERR! Cannot read properties of null (reading 'matches')

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/arvinxx/.npm/_logs/2022-12-23T15_25_27_760Z-debug-0.log
commitlint-config-gitmoji
v2.2.7-beta.1
    at makeError (/Users/arvinxx/CodeProjects/gitmoji-commit-workflow/node_modules/.pnpm/execa@5.1.1/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/arvinxx/CodeProjects/gitmoji-commit-workflow/node_modules/.pnpm/execa@5.1.1/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async module.exports (/Users/arvinxx/CodeProjects/gitmoji-commit-workflow/node_modules/.pnpm/@semantic-release+npm@9.0.1_semantic-release@19.0.5/node_modules/@semantic-release/npm/lib/prepare.js:22:3)
    at async prepare (/Users/arvinxx/CodeProjects/gitmoji-commit-workflow/node_modules/.pnpm/@semantic-release+npm@9.0.1_semantic-release@19.0.5/node_modules/@semantic-release/npm/index.js:68:3)
    at async validator (/Users/arvinxx/CodeProjects/gitmoji-commit-workflow/node_modules/.pnpm/semantic-release@19.0.5/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /Users/arvinxx/CodeProjects/gitmoji-commit-workflow/node_modules/.pnpm/semantic-release@19.0.5/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async Promise.all (index 0)
    at async next (/Users/arvinxx/CodeProjects/gitmoji-commit-workflow/node_modules/.pnpm/p-reduce@2.1.0/node_modules/p-reduce/index.js:16:18) {
  shortMessage: 'Command failed with exit code 1: npm version 2.2.7-beta.1 --userconfig /private/var/folders/3z/f7x4sr8n0qvfxw9jndvd6dj00000gn/T/30e5af0cadafdf31cb2c56c141c6a958/.npmrc --no-git-tag-version --allow-same-version',
  command: 'npm version 2.2.7-beta.1 --userconfig /private/var/folders/3z/f7x4sr8n0qvfxw9jndvd6dj00000gn/T/30e5af0cadafdf31cb2c56c141c6a958/.npmrc --no-git-tag-version --allow-same-version',
  escapedCommand: 'npm version 2.2.7-beta.1 --userconfig "/private/var/folders/3z/f7x4sr8n0qvfxw9jndvd6dj00000gn/T/30e5af0cadafdf31cb2c56c141c6a958/.npmrc" --no-git-tag-version --allow-same-version',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: 'commitlint-config-gitmoji\nv2.2.7-beta.1',
  stderr: "npm ERR! Cannot read properties of null (reading 'matches')\n" +
    '\n' +
    'npm ERR! A complete log of this run can be found in:\n' +
    'npm ERR!     /Users/arvinxx/.npm/_logs/2022-12-23T15_25_27_760Z-debug-0.log',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  pluginName: 'Inline plugin'
}
 ELIFECYCLE  Command failed with exit code 1.
```

Here is the github ci https://github.com/arvinxx/gitmoji-commit-workflow/actions/runs/3766353786/jobs/6402794169#step:7:176

**Comment by arvinxx** [comment]
relative issue: https://github.com/npm/cli/issues/4367

**Comment by travi** [comment]
given that issue in npm, this sounds unrelated to the npm plugin for semantic-release specifically. can this issue be closed, or is there something i'm overlooking that relates it specifically to this plugin?

**Comment by arvinxx** [comment]
> given that issue in npm, this sounds unrelated to the npm plugin for semantic-release specifically. can this issue be closed, or is there something i'm overlooking that relates it specifically to this plugin?

maybe you can try catch this error here? https://github.com/semantic-release/npm/blob/master/lib/prepare.js#L22

**Comment by travi** [comment]
could you help me understand the context of the situation where this would happen when publishing a release? why are linked packages involved in your release pipeline?

**Comment by arvinxx** [comment]
> could you help me understand the context of the situation where this would happen when publishing a release? why are linked packages involved in your release pipeline?

when before publish,  `npm version` is called to upgrade package version (https://github.com/semantic-release/npm/blob/master/lib/prepare.js#L10). In npm v7, it works well. But in npm v8, npm use `@npmcli\arborist` during `npm version`. `@npmcli\arborist` package causes the error, but version actually is bumped. So I think it can be try catch.

**Comment by travi** [comment]
semantic-release is used by many to publish packages using npm v8. i'm trying to understand what is different about your project that results in this error. the issue you linked to suggests it is related to linked packages, but you havent answered my question about my there are linked packages in your project when releasing.

**Comment by arvinxx** [comment]
> semantic-release is used by many to publish packages using npm v8. i'm trying to understand what is different about your project that results in this error. the issue you linked to suggests it is related to linked packages, but you havent answered my question about my there are linked packages in your project when releasing.

i use pnpm workspace for a monorepo(here it is: https://github.com/arvinxx/gitmoji-commit-workflow ). and pnpm use link package to relate package.

**Comment by travi** [comment]
ah, ok. that makes sense. semantic-release does not officially support monorepos because of the additional complexity it can add, such as this situation. we attempt to avoid breaking the ability to build monorepo support on top of our core, like with `multi-semantic-release`, but solving monorepo specific use cases is out of scope for this project. 

without npm providing more information about the reason for the failure, there isnt much that we could do in this plugin if we were to catch the error because we wouldnt be able to distinguish from other errors that should be handled in other ways.

the issue referenced above mentions a recommended fix within project impacted by this situation. it may be possible for `multi-semantic-release` to handle configuring your project according to that recommendation. regardless, this appears to be more related to npm and `multi-semantic-release` in the context of your pnpm project. since that is a configuration that is out of scope for this project, i'm going to close this issue. it may make more sense to open an issue against `multi-semantic-release` instead.
