### ISSUE TITLE
fix vulnerability with http-cache-semantics <4.1.0

### ISSUE THREAD

**Issue by ydekel6** [semantic-release/npm#574]
The module `http-cache-semantics` which is coming from `make-fetch-happen` > from npm@8.19.3 has a high CVE: 
 https://github.com/advisories/GHSA-rc47-6667-2j5j

Need to either push to newer npm@8 or npm@9 version

**Comment by PythonCoderAS** [comment]
There is no newer npm@8 version. I don't see why we need to be locked onto npm@8 either.

**Comment by crudo** [comment]
https://github.com/npm/cli/issues/6151

**Comment by travi** [comment]
this should no longer be a problem
