### ISSUE TITLE
Set --no-workspaces with npm version

### ISSUE THREAD

**Issue by wilbert-abreu** [semantic-release/npm#639]
I need to run "--no-workspaces" or something equivalent to fix this issue https://github.com/npm/cli/issues/4605, anyone know how would I can pass that to the npm version command? https://github.com/semantic-release/npm/blob/master/lib/prepare.js#LL16C42-L16C47

**Comment by wilbert-abreu** [comment]
Seems related to 
https://github.com/semantic-release/npm/pull/534
https://github.com/semantic-release/npm/pull/529

**Comment by travi** [comment]
as mentioned in several other threads, such as https://github.com/semantic-release/npm/pull/634#issuecomment-1591968005, this can be accomplished through standard npm configuration approaches. please attempt to set this flag in your `.npmrc` or `publishConfig` in `package.json`
