### ISSUE TITLE
Publishing failed since update from npm@10.2.4 to npm@10.2.5 with files mentioned in .gitignore

### ISSUE THREAD

**Issue by darlenya** [semantic-release/npm#725]
Hello team,

I have a typescript project. The compiled files are stored in the 'dist' folder. As these generated files should not be added to the GIT repository the folder is added to '.gitignore'.

For publishing the files I have added the entry:
`
  "files": [
    "dist/**/*"
  ],
`
to the package.json file. This is working since years now. But with the change to 'npm@10.2.5' it does not work any more.

if I add the following entry to my package.json file it works again:
`
  "overrides": {
    "npm": "10.2.4"
  }
`
I was not able to track down the error further.

And thank you for this great package.

**Comment by travi** [comment]
Please provide more detail. I use the same approach in many of my packages and have not seen a problem. 

What does "doesn't work" mean? Are you getting an error? A link to a public reproduction would be very helpful

**Comment by darlenya** [comment]
Sorry you are right.
It does only publish package.json and the readme.md. All the other files are ignored. When adding the entry:
`"overrides": { "npm": "10.2.4" }`

All the files in the dist folder were added as expected. Normally the 'files' entry in the package.json should overwrite the '.gitignore'  data. But this does not work any more.

**Comment by darlenya** [comment]
Here is the repo. The readme is describes how to reproduce the issue locally. 

https://github.com/darlenya/semantic-release-demo

**Comment by travi** [comment]
Just a quick thought without investigating yet, I normally only define the directory, without the globbing pattern, `dist/`. It could be possible that npm changed something about globbing in that npm version?  Maybe try removing the pattern beyond the directory?

**Comment by darlenya** [comment]
Yes, you are right, this works. But it is against the documentation of NPM. So I will add a bug there

**Comment by darlenya** [comment]
Issue solved. Need to change the glob pattern
