### ISSUE TITLE
NPM Audit Signatures issue on 11.0.3

### ISSUE THREAD

**Issue by nicholasgriffintn** [semantic-release/npm#763]
Hey, just tried publishing our package which does signature checks before going out to NPM.

Errored with the following on those signature checks:

```
1 package has an invalid attestation:

@semantic-release/npm@11.0.3 (https://registry.npmjs.org/)

Someone might have tampered with this package since it was published on the registry!
```

Seems to be fine with 11.0.2. Also, this version is showing checked on NPM, so not entirely sure on the issue here, maybe something to check out?

**Comment by travi** [comment]
A change was made to what is stored in sigstore when generating provenance before that version of our npm package was published. The latest npm cli is updated to handle the updates details, but it's not included with node yet. See https://github.com/npm/cli/issues/7279 for more details.

**Comment by nicholasgriffintn** [comment]
Ahh yeah I got this error too on our package after publishing, forgot to update.

Thanks for the link.
