### ISSUE TITLE
Verify repository credentials only when publishing

### ISSUE THREAD

**Issue by byCedric** [semantic-release/npm#77]
Ok, so internally at Peakfijn we have a use case for this plugin. One that isn't supported right now, but I feel it might be worth to bring it up here.

We are mostly creating closed source projects. Ones that doesn't get "published" to the repository. However, we do sometimes use the `version` property loaded from the package file to use when debugging. Is it possible to only validate NPM repository credentials when this package is actually used for the publish hook? When this is only validated there, we can use it within the prepare hook and get our version updated without pushing to the repository. This change in the package file is then picked up and committed in our Git Branches plugin (a fork from `semantic-release/git`).

I'm not sure if this is even possible, I do think it is but I'm not sure. And maybe I'm all alone in this, but this would definitely help us! 

Cheers, 
Cedric

**Comment by pvdlg** [comment]
The authentication is verified in both `prepare` and `publish` as long as the `npmPublish` is not set to `false`.
If you don't want to publish an npm repo (and you just want to update the version in the `package.json`) then set the option `npmPublish` to `false`.

**Comment by byCedric** [comment]
Ah, In sorry! Will try that asap!
