### ISSUE TITLE
Array format/style is being changed

### ISSUE THREAD

**Issue by Th3S4mur41** [semantic-release/npm#789]
We use @biomejs in our project to format JS and JSON files including `package.json`

As a result, arrays in the package.json are formatted as a single line:

```json
{
  "keywords": ["webapp", "test", "whatever", "keywords", "and-some-more"],
  "workspaces": ["packages/*"],
}
```

When running semantic release, those arrays are being formatted to multi-line (regardless of the line length).
Which is leading to a the format check failing in CI.

```json
{
  "keywords": [
    "webapp",
    "test",
    "whatever",
    "keywords",
    "and-some-more"
  ],
  "workspaces": [
    "packages/*"
  ],
}
```

I would expect that semantic release should only update the version, but not change the file's format/style.

**Comment by Th3S4mur41** [comment]
@Conaclos FYI

**Comment by Th3S4mur41** [comment]
Closing this, since the format is actually be changed by npm itself when running `npm version`

**Comment by Conaclos** [comment]
I think it could make sense of adding an option to the Biome formatter to expand JSON (and thus match output of `JSON.stringify`). This could be used for config files.
