### ISSUE TITLE
npm ERR! log.http is not a function

### ISSUE THREAD

**Issue by mcarvin8** [semantic-release/npm#809]
<a href='https://hearts.dev/projects/3/users/mcarvin8'><img width='50' alt='' align='right' src='https://hearts.dev/projects/3/users/mcarvin8/tally.svg'></a>

I've been using `@semantic-release/npm` and the other semantic release packages across my various repositories for automated release to NPM.

On my 1 repo (https://github.com/mcarvin8/sf-decomposer), ever since I released my v4.1.0 on this repo (changes made - https://github.com/mcarvin8/sf-decomposer/compare/v4.0.1...v4.1.0), I've had issues with the semantic release job. It is successfully publishing the package to my NPM account, the semantic release bot successfully pushes a commit to update the package.json version, and it's creating the GitHub tag on the repo. However, it's failing to create the GitHub release and it's failing the Release CI job.

I've tried reverting dependencies back to what I originally had, but I'm still hitting the same errors when I'm running my CI job.

Please see this job log - https://github.com/mcarvin8/sf-decomposer/actions/runs/9258132393/job/25467670417

On my other GitHub repos which publish to NPM, I'm not having this issue at all and I'm using the same version of the semantic release packages.

I'm looking for some guidance to resolve these release errors when publishing this repo's package.

**Comment by travi** [comment]
It appears that you have a prepack script defined that is running as a result of npm publishing. Something is failing as part of that script that is not specific to semantic-release and is beyond the scope of support provided here.

**Comment by mcarvin8** [comment]
The pipeline is failing when executing this step in the GitHub workflow, which runs semantic release.

``` yaml
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
```

**Comment by travi** [comment]
Which runs `npm publish`, which triggers your prepack script, which is what is actually failing

**Comment by travi** [comment]
also, your workflow is [using v17 of semantic-release](https://github.com/mcarvin8/sf-decomposer/actions/runs/9258132393/job/25467670417#step:7:8), which is several major versions old. 

please upgrade to the current major. we do not have the bandwidth for older major versions and will not release updates to such old versions, even if a specific issue is identified. only the latest major version will receive updates
