### ISSUE TITLE
[Question] monorepo project

### ISSUE THREAD

**Issue by nikolicjakov** [semantic-release/npm#829]
How could i (or is it possible to) use this plugin in monorepo to update version of multiple applications located in single git repository???

Things like this will not work...

```
plugins: [
  "@semantic-release/commit-analyzer",
  "@semantic-release/release-notes-generator",
  "@semantic-release/gitlab",
  "@semantic-release/changelog",
  [
    "@semantic-release/npm",
    {
      "pkgRoot": "client",
      "npmPublish": false
    },
    {
      "pkgRoot": "server",
      "npmPublish": false
    }
  ],
  ......
```

**Comment by travi** [comment]
we do not officially support monorepos with the projects maintained within this org. there are some community supported extensions to add various levels of monorepo support on top of the core parts maintained here, but support for the community extensions is not provided here
