### ISSUE TITLE
[Bug] plugin does not verify if package.json contain private: true

### ISSUE THREAD

**Issue by kopax** [semantic-release/npm#84]
I have been hitting a case using `npx semantic-release` and this plugin.

The verify step went through, but during the npm release I ended up having an error: 

```bash
npm ERR! This package has been marked as private
npm ERR! Remove the 'private' field from the package.json to publish it.
```

This result in an incomplete release exited with 1.

**Comment by pvdlg** [comment]
It seems to be a duplicate of #4

**Comment by kopax** [comment]
I'm closing in father of #4, but I repost to  include the "private" check.
